spring.application.name=ToDoListWeb

spring.datasource.url= jdbc:postgresql://localhost:5432/ToDoListWeb
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
